# Generated by Django 6.0.6 on 2026-07-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
